language: python
python:
    - "2.7"
env:
    - TEST_TYPE=docs
    - TEST_TYPE=own
    - TEST_TYPE=rubyspec_untranslated
    - TEST_TYPE=translate
install:
    - pip install --use-mirrors fabric
    - fab travis.install_requirements
script: fab travis.run_tests
after_script: fab travis.build_release
notifications:
    email: false
    irc: "irc.freenode.org#topaz"
