language: python
python:
    - "2.7"
env:
    matrix:
        - TEST_TYPE=own
        - TEST_TYPE=translate
install:
    - pip install requests invoke
    - invoke travis.install_requirements
script: invoke travis.run_tests
